collection: "base_api.json"

reporters:
  - junitfull
  - htmlextra
  - cli

reporter:
  junitfull:
    export: "reports/newman_report.xml"
  htmlextra:
    export: "reports/newman_report.html"
    title: "API Test Report"

insecure: true
